# Generated by Django 4.2 on 2024-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='تیتر اسلایدر')),
                ('title_fa', models.TextField(blank=True, null=True, verbose_name='تیتر اسلایدر')),
                ('title_en', models.TextField(blank=True, null=True, verbose_name='تیتر اسلایدر')),
                ('title_ar', models.TextField(blank=True, null=True, verbose_name='تیتر اسلایدر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/sliders', verbose_name='عکس')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن اسلایدر')),
                ('text_fa', models.TextField(blank=True, null=True, verbose_name='متن اسلایدر')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='متن اسلایدر')),
                ('text_ar', models.TextField(blank=True, null=True, verbose_name='متن اسلایدر')),
                ('box_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='تیتر تمام باکس ها')),
                ('box_title_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='تیتر تمام باکس ها')),
                ('box_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='تیتر تمام باکس ها')),
                ('box_title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='تیتر تمام باکس ها')),
                ('is_active', models.BooleanField(default=False, verbose_name='غیر/فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
    ]
