# Generated by Django 4.2 on 2024-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='تیتر')),
                ('text', models.TextField(verbose_name='متن')),
                ('url', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False, verbose_name='غیر/فعال')),
                ('image', models.ImageField(upload_to='uploads/boxes', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'باکس صفحه خانه',
                'verbose_name_plural': 'باکس های صفحه خانه',
            },
        ),
    ]
