# Generated by Django 4.2 on 2024-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebox',
            name='text_ar',
            field=models.TextField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='homebox',
            name='text_en',
            field=models.TextField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='homebox',
            name='text_fa',
            field=models.TextField(null=True, verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='homebox',
            name='title_ar',
            field=models.TextField(null=True, verbose_name='تیتر'),
        ),
        migrations.AddField(
            model_name='homebox',
            name='title_en',
            field=models.TextField(null=True, verbose_name='تیتر'),
        ),
        migrations.AddField(
            model_name='homebox',
            name='title_fa',
            field=models.TextField(null=True, verbose_name='تیتر'),
        ),
    ]
