# Generated by Django 4.2.6 on 2023-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='kind',
            field=models.CharField(choices=[('em', 'ایمیل'), ('ph', 'شماره تماس'), ('loc', 'موقعیت مکانی')], default='em', max_length=200),
        ),
    ]
