# Generated by Django 4.2.6 on 2023-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_contactus_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='text2',
        ),
        migrations.AddField(
            model_name='contactus',
            name='box_text1',
            field=models.TextField(blank=True, null=True, verbose_name='متن اول باکس'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='box_text2',
            field=models.TextField(blank=True, null=True, verbose_name='متن دوم باکس'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='box_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تیتر باکس'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='head_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن سر تیتر'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='kind',
            field=models.CharField(choices=[('em', 'ایمیل'), ('ph', 'شماره تماس'), ('loc', 'موقعیت مکانی')], default='em', max_length=200, verbose_name='نوع باکس'),
        ),
    ]
