# Generated by Django 4.2.6 on 2023-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_remove_contactus_text1_remove_contactus_text2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('em', 'ایمیل'), ('ph', 'شماره تماس'), ('loc', 'موقعیت مکانی')], default='em', max_length=200, verbose_name='نوع باکس')),
                ('box_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='تیتر باکس')),
                ('box_text1', models.TextField(blank=True, null=True, verbose_name='متن اول باکس')),
                ('box_text2', models.TextField(blank=True, null=True, verbose_name='متن دوم باکس')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='box_text1',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='box_text2',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='box_title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='kind',
        ),
    ]
