# Generated by Django 4.2.6 on 2023-10-15 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_contactusbox_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'سرتیتر تماس با ما', 'verbose_name_plural': 'سرتیتر های تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='contactusbox',
            options={'verbose_name': 'جعبه تماس با ما', 'verbose_name_plural': 'جعبه های تماس با ما'},
        ),
    ]
