# Generated by Django 4.2.6 on 2023-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0005_alter_contactus_options_alter_contactusbox_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
        migrations.AddField(
            model_name='contactusbox',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال/غیرفعال'),
        ),
    ]
