# Generated by Django 4.2.6 on 2023-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0006_contactus_is_active_contactusbox_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusbox',
            name='kind',
            field=models.CharField(choices=[('email', 'ایمیل'), ('phone', 'شماره تماس'), ('location', 'موقعیت مکانی')], default='email', max_length=200, verbose_name='نوع باکس'),
        ),
    ]
