# Generated by Django 4.2.6 on 2023-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_alter_product_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptions_ar',
            field=models.TextField(db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions_en',
            field=models.TextField(db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions_fa',
            field=models.TextField(db_index=True, null=True, verbose_name='توضیحات اصلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(max_length=300, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=300, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='threadtype',
            name='title_ar',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام نخ'),
        ),
        migrations.AddField(
            model_name='threadtype',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام نخ'),
        ),
        migrations.AddField(
            model_name='threadtype',
            name='title_fa',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام نخ'),
        ),
    ]
