# Generated by Django 4.2.6 on 2023-11-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_title_alter_product_title_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام نوع محصول')),
                ('title_fa', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام نوع محصول')),
                ('title_en', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام نوع محصول')),
                ('title_ar', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام نوع محصول')),
                ('url_title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'نوع محصول ها',
            },
        ),
        migrations.CreateModel(
            name='SimpleBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام کیسه ساده')),
                ('title_fa', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام کیسه ساده')),
                ('title_en', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام کیسه ساده')),
                ('title_ar', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام کیسه ساده')),
                ('url_title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'گونی ساده',
                'verbose_name_plural': 'گونی های ساده',
            },
        ),
        migrations.CreateModel(
            name='StockBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام کیسه درجه 2')),
                ('title_fa', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام کیسه درجه 2')),
                ('title_en', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام کیسه درجه 2')),
                ('title_ar', models.CharField(db_index=True, max_length=300, null=True, verbose_name='نام کیسه درجه 2')),
                ('url_title', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='نام در url')),
                ('is_active', models.BooleanField(verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'گونی ساده',
                'verbose_name_plural': 'گونی های ساده',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='thread',
        ),
        migrations.DeleteModel(
            name='ThreadType',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.producttype', verbose_name='نوع محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='simple_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.simplebag', verbose_name='گونی ساده'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_bag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.stockbag', verbose_name='گونی درجه 2'),
        ),
    ]
